# Generated by Django 3.2.23 on 2023-12-06 06:05

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231122_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'User with this cpf already exists.'}, max_length=14, unique=True, validators=[utils.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email already exists.'}, max_length=255, unique=True),
        ),
    ]
